
package com.shehatamilo;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saySomething", targetNamespace = "http://hello/", className = "com.shehatamilo.SaySomething")
    @ResponseWrapper(localName = "saySomethingResponse", targetNamespace = "http://hello/", className = "com.shehatamilo.SaySomethingResponse")
    @Action(input = "http://hello/HelloWorld/saySomethingRequest", output = "http://hello/HelloWorld/saySomethingResponse")
    public String saySomething();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.shehatamilo.DummyData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://hello/", className = "com.shehatamilo.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://hello/", className = "com.shehatamilo.GetDataResponse")
    @Action(input = "http://hello/HelloWorld/getDataRequest", output = "http://hello/HelloWorld/getDataResponse")
    public DummyData getData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
